#!/usr/bin/env bash
# BEST
zb=1
while [[ $zb -le 10 ]]
do
	if [[ $zb -eq 4 ]];
then
		echo "bad luck";
	elif [[ $zb -eq 8 ]]; then
		echo "good luck";
	else
		echo "Best School";
	fi
	zb=$(( zb+1 ));
done
